name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: cmake -DCMAKE_BUILD_TYPE=Debug -Wno-dev .
    - name: Build Debug
      run: CXX=clang++ make VERBOSE=1 debug;
    - name: Tests
      run: ctest -VV
